#Custom aliases for quick navigation and command

alias loj='cd /mnt/f/OJs/lightoj'
alias cf='cd /mnt/f/OJs/codeforces'
alias uva='cd /mnt/f/OJs/Uva'
alias oj='cd /mnt/f/OJs'
alias dt='cd /mnt/c/Users/Asus/Desktop'
alias f='cd /mnt/f/'
alias ..='cd ..'
alias ...='cd ..; cd ..'
alias ....='cd ..; cd ..; cd ..'
alias bashrc='vim ~/.bashrc'
alias vimrc='vim ~/.vimrc'
alias loadbash='source ~/.bashrc'
alias la='ls -la'
alias pip='pip3'
alias python='python3'
